"""Guide-agent deployment controllers."""

from .abcg import ABCGController
from .abcg_v2 import (
    ABCGv2Config,
    ABCGv2Controller,
    ConvergenceStateMachine,
    ControlOutput,
    EpisodeResult,
    integrate_guide_positions,
    nominal_guide_velocity,
)
from .assignment import (
    AssignmentConfig,
    AssignmentResult,
    IdentityPreservingAssigner,
    assign_cyclic_order_preserving,
    assign_guides_to_targets,
)
from .analytic_arc import (
    AnalyticArcPlan,
    PhaseOptimizationResult,
    analytic_equal_arc_gap,
    analytic_uniform_cost,
    optimize_equal_arc_phase,
    periodic_site_sets_equal,
    plan_analytic_equal_arc,
)
from .coverage_cvt import BoundaryCVTController
from .legacy_center_radius import LegacyCenterRadiusController
from .periodic_arc_cvt import (
    CoveragePlan,
    PeriodicArcCVT,
    PeriodicArcCVTConfig,
    equal_arc_target_s,
    plan_equal_arc_coverage,
    plan_periodic_arc_coverage,
    periodic_uniform_coverage_cost,
)
from .random_deployment import RandomDeploymentController
from .resources import ResourceDecision, ResourcePolicy, ResourcePolicyConfig, allocate_guide_resources
from .resources_v2 import RobustResourceConfig, RobustResourceDecision, allocate_robust_resources
from .routing import (
    ClearanceCertificate,
    PairwiseRouteMatrix,
    ROUTE_METHODS,
    RoutePath,
    RoutingConfig,
    build_pairwise_route_matrix,
    route_boundary_corridor,
    route_guide_to_target,
    route_straight,
    route_visibility_graph,
)
from .safety import SafetyProjectionResult, VelocitySafetyConfig, project_velocity_safety
from .safety_v2 import (
    ProjectionResidualCertificate,
    VelocityProjectionCertificate,
    VelocityProjectionConfig,
    VelocityProjectionProblem,
    VelocitySafetyV2Result,
    ZOHDenseCheckCertificate,
    build_velocity_projection_problem,
    project_velocity_safety_v2,
    projection_residual_certificate,
    solve_velocity_projection,
    zoh_dense_check,
)
from .static_circle import StaticCircleController
from .waypoint import (
    FixedWaypointPaths,
    PATH_SCHEMA,
    WaypointEpisodeResult,
    WaypointEpisodeRunner,
    WaypointEvent,
    WaypointRunnerConfig,
    WaypointSafetyRequest,
    WaypointSafetyResponse,
)

__all__ = [
    "ABCGController",
    "ABCGv2Config",
    "ABCGv2Controller",
    "AnalyticArcPlan",
    "AssignmentConfig",
    "AssignmentResult",
    "ClearanceCertificate",
    "BoundaryCVTController",
    "LegacyCenterRadiusController",
    "IdentityPreservingAssigner",
    "CoveragePlan",
    "ConvergenceStateMachine",
    "ControlOutput",
    "EpisodeResult",
    "FixedWaypointPaths",
    "PeriodicArcCVT",
    "PeriodicArcCVTConfig",
    "PATH_SCHEMA",
    "PairwiseRouteMatrix",
    "PhaseOptimizationResult",
    "ProjectionResidualCertificate",
    "RandomDeploymentController",
    "ResourceDecision",
    "ResourcePolicy",
    "ResourcePolicyConfig",
    "RobustResourceConfig",
    "RobustResourceDecision",
    "ROUTE_METHODS",
    "RoutePath",
    "RoutingConfig",
    "StaticCircleController",
    "SafetyProjectionResult",
    "VelocitySafetyConfig",
    "VelocityProjectionCertificate",
    "VelocityProjectionConfig",
    "VelocityProjectionProblem",
    "VelocitySafetyV2Result",
    "ZOHDenseCheckCertificate",
    "WaypointEpisodeResult",
    "WaypointEpisodeRunner",
    "WaypointEvent",
    "WaypointRunnerConfig",
    "WaypointSafetyRequest",
    "WaypointSafetyResponse",
    "equal_arc_target_s",
    "analytic_equal_arc_gap",
    "analytic_uniform_cost",
    "allocate_guide_resources",
    "allocate_robust_resources",
    "assign_cyclic_order_preserving",
    "assign_guides_to_targets",
    "build_pairwise_route_matrix",
    "build_velocity_projection_problem",
    "plan_equal_arc_coverage",
    "plan_periodic_arc_coverage",
    "periodic_uniform_coverage_cost",
    "optimize_equal_arc_phase",
    "periodic_site_sets_equal",
    "plan_analytic_equal_arc",
    "route_boundary_corridor",
    "route_guide_to_target",
    "route_straight",
    "route_visibility_graph",
    "project_velocity_safety",
    "project_velocity_safety_v2",
    "projection_residual_certificate",
    "solve_velocity_projection",
    "integrate_guide_positions",
    "nominal_guide_velocity",
    "zoh_dense_check",
]
